### ISSUE TITLE
Rework the evidence algorithm to also include the number sources

### ISSUE THREAD

**Issue by xJREB** [xJREB/service-based-antipatterns#107]
I just discovered that `Nanoservices` (https://xjreb.github.io/service-based-antipatterns/?antipattern=Nanoservices) has an evidence score of `low`, even though it seems to have one of the largest number of source (8). Maybe it would be a good idea to include not only the citations of the sources, but also their absolute number.

**Comment by boceckts** [comment]
I proposed a similar strategy by using the number of sources as index ofor their popularity in #103
I added icons to the antipatterns that represent the number of sources and added a sort by number of sources to the sort field.

**Comment by xJREB** [comment]
OK, this is good, because it respects the number of sources as an indicator of an antipattern's importance or reliability. It is "bad", because it adds an additional concept and therefore complexity to the UI. Is your notion of `popularity` very different from your notion of `evidence` and does it make sense to keep both concepts? If there is no real value for the end-user to have both, I see no sense in NOT merging them.

So the question is: If I wanna know, if the antipattern I'm looking at is widely accepted and therefore probably reliable, do I need both of these measures separately for this? In case both have different values, which one do I trust? My suggestion would therefore be to merge this into one measure that represents the antipattern's acceptance and reliability. Maybe you could even call it `popularity` instead of `evidence`, even though that sounds somewhat odd for an antipattern... 🤔 Not sure... What do you guys think? Does that make sense? Am I missing something?

**Comment by xJREB** [comment]
Hmm, my intuitive feeling would be that several sources should count nearly as much as one source with a lot of citations. Maybe something like this:

![image](https://user-images.githubusercontent.com/3702778/51465002-2ddff600-1d67-11e9-8860-598fa1668758.png)

So, each source counts a least 1 plus the log of the number of citations, e.g an antipattern with one source with 1,000 citations has an evidence of 4 while an antipattern with 4 sources with 1 citation each has also an evidence of 4. How does this sound?

Also, what is the current mapping algortihm of the evidence rank to the labels `low`, `medium`, and `high`?

**Comment by boceckts** [comment]
Ok, sounds like a good algorithm. We checked the range in which most of the antipatterns' evidence score appeared and used this as medium.
With your formula the evidence ranges from 0.x to 20.x with most evidence scores between 2 and 6

**Comment by boceckts** [comment]
With your formula and the categories
```
low: 1
medium: 3,
high: 10,
very high: 20
```
3 antipatterns fall in the low category, 28 in the medium category, 4 in the high category and only 2 antipatterns in the very high category
