### ISSUE TITLE
Rework heading and text of antipattern detail view

### ISSUE THREAD

**Issue by tschechlovdev** [xJREB/service-based-antipatterns#28]
The heading and the corresponding text have to much space between each other, so it is hard to see that they belong together.

**Comment by boceckts** [comment]
Simply increasing top padding:

![grafik](https://user-images.githubusercontent.com/15340757/49301695-801e3c80-f4c5-11e8-9df6-ba6529a3beab.png)

![grafik](https://user-images.githubusercontent.com/15340757/49301657-6c72d600-f4c5-11e8-8adc-cc9fa0db9d0b.png)


Completely new column based layout:

![grafik](https://user-images.githubusercontent.com/15340757/49301851-dc815c00-f4c5-11e8-8abb-bbfcd1fa806b.png)

![grafik](https://user-images.githubusercontent.com/15340757/49301998-2e29e680-f4c6-11e8-8360-5d9c2af7762b.png)

Personally I like the column layout more, but I'm also open to a completely different approach.

**Comment by mpoqq** [comment]
Justus also preferred the column layout. So please create a pull request. Thanks =)
