### ISSUE TITLE
Create a link to the GitHub repo

### ISSUE THREAD

**Issue by xJREB** [xJREB/service-based-antipatterns#35]
Create a link to the GitHub repository using a GitHub icon. Possible location: top right corner of the navbar.

**Comment by boceckts** [comment]
How about this one?

![image](https://user-images.githubusercontent.com/15340757/49009602-4a99ec00-f171-11e8-9f8f-9480c36cc065.png)

![image](https://user-images.githubusercontent.com/15340757/49009621-57b6db00-f171-11e8-82a8-3fe081e60267.png)

**Comment by xJREB** [comment]
Yeah, should be fine. :)
Some more examples:
- https://router.vuejs.org
- http://getbootstrap.com
- https://ng-bootstrap.github.io/#/home

**Comment by xJREB** [comment]
Yeah, this looks better. 👍
